# Generated by Django 2.2.7 on 2019-12-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('shipment', models.CharField(choices=[('l', 'list'), ('p', 'paczka'), ('k', 'kurier')], max_length=1)),
            ],
        ),
    ]
