# Generated by Django 2.2.7 on 2019-12-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='product_ratings',
        ),
    ]
